# Generated by Django 2.0 on 2019-02-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_projectmodel_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='site',
        ),
    ]
