# Generated by Django 2.0 on 2019-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20190217_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfilemodel',
            name='reason',
            field=models.CharField(default='无', max_length=100, null=True, verbose_name='审核理由'),
        ),
    ]
